//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geeks.DependencyInjection.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geeks.DependencyInjection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method bound with your request has thrown an exception. See InnerException for more details..
        /// </summary>
        internal static string Exception_BoundMethodException {
            get {
                return ResourceManager.GetString("Exception_BoundMethodException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Binding found for Request &apos;{0}&apos;..
        /// </summary>
        internal static string Exception_NoBindingFound {
            get {
                return ResourceManager.GetString("Exception_NoBindingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type to resolve has no valid constructor defined. Only public constructors can be used for creation..
        /// </summary>
        internal static string Exception_NoValidCtor {
            get {
                return ResourceManager.GetString("Exception_NoValidCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Type to resolve has unresolvable constructor parameters..
        /// </summary>
        internal static string Exception_UnresolvedCtorParams {
            get {
                return ResourceManager.GetString("Exception_UnresolvedCtorParams", resourceCulture);
            }
        }
    }
}
